version: "3"

services:
  webserver:
    image: "nginx:stable-alpine"
    container_name: "website_container"
    ports:
      - "80:80"
    volumes:
      - "./build:/webdata"
      - "./custom-nginx.conf:/etc/nginx/conf.d/default.conf"
  npm:
    image: "node:18-alpine"
    container_name: "nodejs"
    volumes:
      - "./:/webdata"
    working_dir: "/webdata"

