export const TOKEN_KEY = 'token'
export const USER_LOGIN_KEY = 'user-login'
export const SELECTED_CONVERSATION = 'selected-conversation'
export const SURVEY_POST_REQUEST = 'survey-post-request'
export const PROFILE_ID = 'profileId'
export const CVURL = 'cvUrl'
export const DEFAULT_LANGUAGE = 'default-language'
export const POST_UPDATE_ID = 'survey-post-update-id'
