export const BUSINESS_DASHBOARD_PAGE = '/doanh-nghiep/bai-viet'
export const CREATE_RECRUITMENT_POST_PAGE = '/them-bai-viet/tuyen-dung'
export const CREATE_SURVEY_POST_PAGE = '/them-bai-viet/khao-sat'
export const SEARCH_PAGE = '/tim-kiem'
export const REGISTER_BUSINESS_PAGE = '/dang-ky/doanh-nghiep'
export const REGISTER_STUDENT_PAGE = '/dang-ky/sinh-vien'
